/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package msystem;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author never
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form FinalOrder
     */
    public MainMenu() {
        initComponents();
        Cart.resetCart();
        getList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgroupMains = new javax.swing.ButtonGroup();
        rdgroupSides = new javax.swing.ButtonGroup();
        btnResetOrder = new javax.swing.JButton();
        btnFinalizeOrder = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rdbtnHam = new javax.swing.JRadioButton();
        rdbtnChknF = new javax.swing.JRadioButton();
        rdbtnPizza = new javax.swing.JRadioButton();
        rdbtnHamCh = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdbtnFriesL = new javax.swing.JRadioButton();
        rdbtnFriesM = new javax.swing.JRadioButton();
        rdbtnFriesS = new javax.swing.JRadioButton();
        rdbtnNoneSide = new javax.swing.JRadioButton();
        rdbtnNoneMain = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnAddOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCart = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        btnRemoveCartItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnResetOrder.setText("Reset Order");
        btnResetOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetOrderMouseClicked(evt);
            }
        });

        btnFinalizeOrder.setText("Finalize Order");
        btnFinalizeOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizeOrderMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rdgroupMains.add(rdbtnHam);
        rdbtnHam.setText("Hamburger");
        rdbtnHam.setToolTipText("");

        rdgroupMains.add(rdbtnChknF);
        rdbtnChknF.setText("Chicken Fingers");
        rdbtnChknF.setToolTipText("");

        rdgroupMains.add(rdbtnPizza);
        rdbtnPizza.setText("Pizza");
        rdbtnPizza.setToolTipText("");

        rdgroupMains.add(rdbtnHamCh);
        rdbtnHamCh.setText("Cheeseburger");
        rdbtnHamCh.setToolTipText("");

        jLabel2.setText("Mains");

        jLabel3.setText("Sides");

        rdgroupSides.add(rdbtnFriesL);
        rdbtnFriesL.setText("Large Fries");

        rdgroupSides.add(rdbtnFriesM);
        rdbtnFriesM.setText("Medium Fries");

        rdgroupSides.add(rdbtnFriesS);
        rdbtnFriesS.setText("Small Fries");
        rdbtnFriesS.setActionCommand("Small Fries");

        rdgroupSides.add(rdbtnNoneSide);
        rdbtnNoneSide.setSelected(true);
        rdbtnNoneSide.setText("None");

        rdgroupMains.add(rdbtnNoneMain);
        rdbtnNoneMain.setSelected(true);
        rdbtnNoneMain.setText("None");
        rdbtnNoneMain.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnNoneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnChknF, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(rdbtnHam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnNoneSide, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnFriesS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnFriesM, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnFriesL, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnHamCh, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdbtnHam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnHamCh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnPizza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnChknF))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnNoneMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnFriesL)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnFriesM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnFriesS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnNoneSide)
                .addContainerGap())
        );

        jLabel1.setText("Menu");

        btnAddOrder.setText("Add to Order");
        btnAddOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddOrderMouseClicked(evt);
            }
        });

        lstCart.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstCart);

        jLabel4.setText("Cart");

        btnRemoveCartItem.setText("Remove from Cart");
        btnRemoveCartItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveCartItemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnResetOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btnAddOrder)
                        .addGap(18, 18, 18)
                        .addComponent(btnFinalizeOrder)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRemoveCartItem)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveCartItem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFinalizeOrder)
                        .addComponent(btnAddOrder))
                    .addComponent(btnResetOrder))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizeOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizeOrderMouseClicked
        // TODO add your handling code here:
        new ShowOrder().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFinalizeOrderMouseClicked

    private void btnResetOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetOrderMouseClicked
        // TODO add your handling code here:
        Cart.resetCart();
        getList();
    }//GEN-LAST:event_btnResetOrderMouseClicked

    private void btnAddOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddOrderMouseClicked
        // TODO add your handling code here:
        if(rdbtnHam.isSelected()){
            Cart.addToCart(rdbtnHam.getText());
        }
        else if(rdbtnHamCh.isSelected()){
            Cart.addToCart(rdbtnHamCh.getText());
        }
        else if(rdbtnChknF.isSelected()){
            Cart.addToCart(rdbtnChknF.getText());
        }
        else if(rdbtnPizza.isSelected()){
            Cart.addToCart(rdbtnPizza.getText());
        }
        if(rdbtnFriesL.isSelected()){
            Cart.addToCart(rdbtnFriesL.getText());
        }
        else if(rdbtnFriesM.isSelected()){
            Cart.addToCart(rdbtnFriesM.getText());
        }
        else if(rdbtnFriesS.isSelected()){
            Cart.addToCart(rdbtnFriesS.getText());
        }
        getList();
        
    }//GEN-LAST:event_btnAddOrderMouseClicked

    private void btnRemoveCartItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveCartItemMouseClicked
        // TODO add your handling code here:
        Cart.removeFromCart(lstCart.getSelectedValue().toString());
        getList();
    }//GEN-LAST:event_btnRemoveCartItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    public static void getList(){
        ArrayList<String> list = new ArrayList<>();
        list = Cart.Cart;
        DefaultListModel model = new DefaultListModel();
        model.addAll(list);
        lstCart.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnFinalizeOrder;
    private javax.swing.JButton btnRemoveCartItem;
    private javax.swing.JButton btnResetOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JList<String> lstCart;
    private javax.swing.JRadioButton rdbtnChknF;
    private javax.swing.JRadioButton rdbtnFriesL;
    private javax.swing.JRadioButton rdbtnFriesM;
    private javax.swing.JRadioButton rdbtnFriesS;
    private javax.swing.JRadioButton rdbtnHam;
    private javax.swing.JRadioButton rdbtnHamCh;
    private javax.swing.JRadioButton rdbtnNoneMain;
    private javax.swing.JRadioButton rdbtnNoneSide;
    private javax.swing.JRadioButton rdbtnPizza;
    private javax.swing.ButtonGroup rdgroupMains;
    private javax.swing.ButtonGroup rdgroupSides;
    // End of variables declaration//GEN-END:variables
}
